[features]
seeds = false
[programs.localnet]
canvas = "BJCgYB56gxD9WsVaQanFoNByarTQm7qhsVLVKT6We8jn"
[programs.devnet]
canvas = "BJCgYB56gxD9WsVaQanFoNByarTQm7qhsVLVKT6We8jn"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "dev_keys/account1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
